-- ============================================================
-- Phase 2 – Performance des campagnes marketing
-- ============================================================

-- 1. Performance globale par type de campagne
SELECT
    CAMPAIGN_TYPE,
    COUNT(*) AS NB_CAMPAGNES,
    SUM(BUDGET) AS BUDGET_TOTAL,
    AVG(BUDGET) AS BUDGET_MOYEN,
    SUM(REACH) AS REACH_TOTAL,
    AVG(CONVERSION_RATE) AS TAUX_CONVERSION_MOYEN,
    SUM(BUDGET) / NULLIF(SUM(REACH), 0) AS COUT_PAR_REACH
FROM ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN
GROUP BY 1
ORDER BY TAUX_CONVERSION_MOYEN DESC;

-- 2. Performance par catégorie produit
SELECT
    PRODUCT_CATEGORY,
    COUNT(*) AS NB_CAMPAGNES,
    SUM(BUDGET) AS BUDGET_TOTAL,
    SUM(REACH) AS REACH_TOTAL,
    AVG(CONVERSION_RATE) AS TAUX_CONVERSION_MOYEN,
    SUM(BUDGET * CONVERSION_RATE) AS BUDGET_PONDERE_CONVERSION
FROM ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN
GROUP BY 1
ORDER BY TAUX_CONVERSION_MOYEN DESC;

-- 3. Performance par audience cible
SELECT
    TARGET_AUDIENCE,
    COUNT(*) AS NB_CAMPAGNES,
    AVG(BUDGET) AS BUDGET_MOYEN,
    AVG(REACH) AS REACH_MOYEN,
    AVG(CONVERSION_RATE) AS TAUX_CONVERSION_MOYEN
FROM ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN
GROUP BY 1
ORDER BY TAUX_CONVERSION_MOYEN DESC;

-- 4. Performance par région
SELECT
    REGION,
    COUNT(*) AS NB_CAMPAGNES,
    SUM(BUDGET) AS BUDGET_TOTAL,
    SUM(REACH) AS REACH_TOTAL,
    AVG(CONVERSION_RATE) AS TAUX_CONVERSION_MOYEN
FROM ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN
GROUP BY 1
ORDER BY TAUX_CONVERSION_MOYEN DESC;

-- 5. Campagnes les plus efficaces (top 20 par ROI estimé)
SELECT
    CAMPAIGN_ID,
    CAMPAIGN_NAME,
    CAMPAIGN_TYPE,
    PRODUCT_CATEGORY,
    TARGET_AUDIENCE,
    REGION,
    BUDGET,
    REACH,
    CONVERSION_RATE,
    REACH * CONVERSION_RATE AS CONVERSIONS_ESTIMEES,
    BUDGET / NULLIF(REACH * CONVERSION_RATE, 0) AS COUT_PAR_CONVERSION
FROM ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN
ORDER BY COUT_PAR_CONVERSION ASC NULLS LAST
LIMIT 20;

-- 6. Évolution temporelle des campagnes
SELECT
    YEAR(START_DATE) AS ANNEE,
    COUNT(*) AS NB_CAMPAGNES,
    SUM(BUDGET) AS BUDGET_TOTAL,
    AVG(REACH) AS REACH_MOYEN,
    AVG(CONVERSION_RATE) AS TAUX_CONVERSION_MOYEN
FROM ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN
GROUP BY 1
ORDER BY 1;

-- 7. Impact avis produits sur les catégories
SELECT
    pr.PRODUCT_CATEGORY,
    COUNT(DISTINCT pr.REVIEW_ID) AS NB_AVIS,
    AVG(pr.RATING) AS NOTE_MOYENNE,
    SUM(pr.HELPFUL_VOTES) AS TOTAL_VOTES_UTILES,
    COUNT(DISTINCT mc.CAMPAIGN_ID) AS NB_CAMPAGNES
FROM ANYCOMPANY_LAB.SILVER.PRODUCT_REVIEWS_CLEAN pr
LEFT JOIN ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN mc
    ON pr.PRODUCT_CATEGORY = mc.PRODUCT_CATEGORY
GROUP BY 1
ORDER BY NOTE_MOYENNE DESC;

-- 8. Analyse service client
SELECT
    ISSUE_CATEGORY,
    COUNT(*) AS NB_INTERACTIONS,
    AVG(DURATION_MINUTES) AS DUREE_MOYENNE,
    AVG(CUSTOMER_SATISFACTION) AS SATISFACTION_MOYENNE,
    SUM(CASE WHEN RESOLUTION_STATUS = 'Resolved' THEN 1 ELSE 0 END)::FLOAT / COUNT(*) AS TAUX_RESOLUTION
FROM ANYCOMPANY_LAB.SILVER.CUSTOMER_SERVICE_INTERACTIONS_CLEAN
GROUP BY 1
ORDER BY NB_INTERACTIONS DESC;

-- 9. Analyse logistique : statut des expéditions
SELECT
    STATUS,
    COUNT(*) AS NB_EXPEDITIONS,
    AVG(SHIPPING_COST) AS COUT_MOYEN,
    AVG(DATEDIFF('DAY', SHIP_DATE, ESTIMATED_DELIVERY)) AS DELAI_MOYEN_JOURS
FROM ANYCOMPANY_LAB.SILVER.LOGISTICS_AND_SHIPPING_CLEAN
GROUP BY 1
ORDER BY NB_EXPEDITIONS DESC;

-- 10. Ruptures de stock potentielles
SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY,
    REGION,
    COUNTRY,
    WAREHOUSE,
    CURRENT_STOCK,
    REORDER_POINT,
    LEAD_TIME,
    LAST_RESTOCK_DATE,
    CASE WHEN CURRENT_STOCK <= REORDER_POINT THEN 'ALERTE RUPTURE' ELSE 'OK' END AS STATUT_STOCK
FROM ANYCOMPANY_LAB.SILVER.INVENTORY_CLEAN
WHERE CURRENT_STOCK <= REORDER_POINT
ORDER BY CURRENT_STOCK ASC
LIMIT 50;
