-- ============================================================
-- Phase 1 – Étape 5 : Data Cleaning (BRONZE → SILVER)
-- ============================================================

USE DATABASE ANYCOMPANY_LAB;
CREATE SCHEMA IF NOT EXISTS SILVER;

-- ============================================================
-- 1. FINANCIAL_TRANSACTIONS_CLEAN
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.FINANCIAL_TRANSACTIONS_CLEAN AS
SELECT
    TRANSACTION_ID,
    TRANSACTION_DATE,
    TRANSACTION_TYPE,
    AMOUNT,
    PAYMENT_METHOD,
    TRIM(ENTITY) AS ENTITY,
    TRIM(REGION) AS REGION,
    ACCOUNT_CODE
FROM ANYCOMPANY_LAB.BRONZE.FINANCIAL_TRANSACTIONS
WHERE TRANSACTION_ID IS NOT NULL
  AND TRANSACTION_DATE IS NOT NULL
  AND AMOUNT > 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID ORDER BY TRANSACTION_DATE DESC) = 1;

-- ============================================================
-- 2. PROMOTIONS_CLEAN
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.PROMOTIONS_CLEAN AS
SELECT
    PROMOTION_ID,
    TRIM(PRODUCT_CATEGORY) AS PRODUCT_CATEGORY,
    TRIM(PROMOTION_TYPE) AS PROMOTION_TYPE,
    DISCOUNT_PERCENTAGE,
    START_DATE,
    END_DATE,
    TRIM(REGION) AS REGION
FROM ANYCOMPANY_LAB.BRONZE.PROMOTIONS_DATA
WHERE PROMOTION_ID IS NOT NULL
  AND START_DATE IS NOT NULL
  AND END_DATE IS NOT NULL
  AND START_DATE <= END_DATE
  AND DISCOUNT_PERCENTAGE > 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY PROMOTION_ID ORDER BY START_DATE DESC) = 1;

-- ============================================================
-- 3. MARKETING_CAMPAIGNS_CLEAN
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN AS
SELECT
    CAMPAIGN_ID,
    TRIM(CAMPAIGN_NAME) AS CAMPAIGN_NAME,
    TRIM(CAMPAIGN_TYPE) AS CAMPAIGN_TYPE,
    TRIM(PRODUCT_CATEGORY) AS PRODUCT_CATEGORY,
    TRIM(TARGET_AUDIENCE) AS TARGET_AUDIENCE,
    START_DATE,
    END_DATE,
    TRIM(REGION) AS REGION,
    BUDGET,
    REACH,
    CONVERSION_RATE
FROM ANYCOMPANY_LAB.BRONZE.MARKETING_CAMPAIGNS
WHERE CAMPAIGN_ID IS NOT NULL
  AND START_DATE IS NOT NULL
  AND END_DATE IS NOT NULL
  AND START_DATE <= END_DATE
  AND BUDGET > 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY CAMPAIGN_ID ORDER BY START_DATE DESC) = 1;

-- ============================================================
-- 4. CUSTOMER_DEMOGRAPHICS_CLEAN
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.CUSTOMER_DEMOGRAPHICS_CLEAN AS
SELECT
    CUSTOMER_ID,
    TRIM(NAME) AS NAME,
    DATE_OF_BIRTH,
    TRIM(UPPER(GENDER)) AS GENDER,
    TRIM(REGION) AS REGION,
    TRIM(COUNTRY) AS COUNTRY,
    TRIM(CITY) AS CITY,
    TRIM(MARITAL_STATUS) AS MARITAL_STATUS,
    ANNUAL_INCOME
FROM ANYCOMPANY_LAB.BRONZE.CUSTOMER_DEMOGRAPHICS
WHERE CUSTOMER_ID IS NOT NULL
  AND ANNUAL_INCOME > 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY DATE_OF_BIRTH) = 1;

-- ============================================================
-- 5. CUSTOMER_SERVICE_INTERACTIONS_CLEAN
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.CUSTOMER_SERVICE_INTERACTIONS_CLEAN AS
SELECT
    INTERACTION_ID,
    INTERACTION_DATE,
    TRIM(INTERACTION_TYPE) AS INTERACTION_TYPE,
    TRIM(ISSUE_CATEGORY) AS ISSUE_CATEGORY,
    DESCRIPTION,
    DURATION_MINUTES,
    TRIM(RESOLUTION_STATUS) AS RESOLUTION_STATUS,
    TRIM(FOLLOW_UP_REQUIRED) AS FOLLOW_UP_REQUIRED,
    CUSTOMER_SATISFACTION
FROM ANYCOMPANY_LAB.BRONZE.CUSTOMER_SERVICE_INTERACTIONS
WHERE INTERACTION_ID IS NOT NULL
  AND INTERACTION_DATE IS NOT NULL
  AND DURATION_MINUTES > 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY INTERACTION_ID ORDER BY INTERACTION_DATE DESC) = 1;

-- ============================================================
-- 6. PRODUCT_REVIEWS_CLEAN
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.PRODUCT_REVIEWS_CLEAN AS
SELECT
    REVIEW_ID,
    PRODUCT_ID,
    REVIEWER_ID,
    TRIM(REVIEWER_NAME) AS REVIEWER_NAME,
    HELPFUL_VOTES,
    TOTAL_VOTES,
    RATING,
    REVIEW_DATE::DATE AS REVIEW_DATE,
    TRIM(REVIEW_TITLE) AS REVIEW_TITLE,
    REVIEW_TEXT,
    TRIM(PRODUCT_CATEGORY) AS PRODUCT_CATEGORY,
    TRIM(PRODUCT_SUBCATEGORY) AS PRODUCT_SUBCATEGORY,
    PRODUCT_DESCRIPTION
FROM ANYCOMPANY_LAB.BRONZE.PRODUCT_REVIEWS
WHERE REVIEW_ID IS NOT NULL
  AND RATING BETWEEN 1 AND 5
  AND REVIEW_DATE IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY REVIEW_ID ORDER BY REVIEW_DATE DESC) = 1;

-- ============================================================
-- 7. INVENTORY_CLEAN (JSON → table relationnelle)
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.INVENTORY_CLEAN AS
SELECT
    f.VALUE:"product_id"::VARCHAR AS PRODUCT_ID,
    TRIM(f.VALUE:"product_category"::VARCHAR) AS PRODUCT_CATEGORY,
    TRIM(f.VALUE:"region"::VARCHAR) AS REGION,
    TRIM(f.VALUE:"country"::VARCHAR) AS COUNTRY,
    TRIM(f.VALUE:"warehouse"::VARCHAR) AS WAREHOUSE,
    f.VALUE:"current_stock"::NUMBER AS CURRENT_STOCK,
    f.VALUE:"reorder_point"::NUMBER AS REORDER_POINT,
    f.VALUE:"lead_time"::NUMBER AS LEAD_TIME,
    f.VALUE:"last_restock_date"::DATE AS LAST_RESTOCK_DATE
FROM ANYCOMPANY_LAB.BRONZE.INVENTORY,
     LATERAL FLATTEN(INPUT => RAW_JSON) f
WHERE f.VALUE:"product_id" IS NOT NULL
  AND f.VALUE:"current_stock"::NUMBER >= 0;

-- ============================================================
-- 8. STORE_LOCATIONS_CLEAN (JSON → table relationnelle)
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.STORE_LOCATIONS_CLEAN AS
SELECT
    f.VALUE:"store_id"::VARCHAR AS STORE_ID,
    TRIM(f.VALUE:"store_name"::VARCHAR) AS STORE_NAME,
    TRIM(f.VALUE:"store_type"::VARCHAR) AS STORE_TYPE,
    TRIM(f.VALUE:"region"::VARCHAR) AS REGION,
    TRIM(f.VALUE:"country"::VARCHAR) AS COUNTRY,
    TRIM(f.VALUE:"city"::VARCHAR) AS CITY,
    TRIM(f.VALUE:"address"::VARCHAR) AS ADDRESS,
    f.VALUE:"postal_code"::VARCHAR AS POSTAL_CODE,
    f.VALUE:"square_footage"::NUMBER(10,2) AS SQUARE_FOOTAGE,
    f.VALUE:"employee_count"::NUMBER AS EMPLOYEE_COUNT
FROM ANYCOMPANY_LAB.BRONZE.STORE_LOCATIONS,
     LATERAL FLATTEN(INPUT => RAW_JSON) f
WHERE f.VALUE:"store_id" IS NOT NULL;

-- ============================================================
-- 9. LOGISTICS_AND_SHIPPING_CLEAN
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.LOGISTICS_AND_SHIPPING_CLEAN AS
SELECT
    SHIPMENT_ID,
    ORDER_ID,
    SHIP_DATE,
    ESTIMATED_DELIVERY,
    TRIM(SHIPPING_METHOD) AS SHIPPING_METHOD,
    TRIM(STATUS) AS STATUS,
    SHIPPING_COST,
    TRIM(DESTINATION_REGION) AS DESTINATION_REGION,
    TRIM(DESTINATION_COUNTRY) AS DESTINATION_COUNTRY,
    TRIM(CARRIER) AS CARRIER
FROM ANYCOMPANY_LAB.BRONZE.LOGISTICS_AND_SHIPPING
WHERE SHIPMENT_ID IS NOT NULL
  AND SHIP_DATE IS NOT NULL
  AND SHIPPING_COST >= 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY SHIPMENT_ID ORDER BY SHIP_DATE DESC) = 1;

-- ============================================================
-- 10. SUPPLIER_INFORMATION_CLEAN
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.SUPPLIER_INFORMATION_CLEAN AS
SELECT
    SUPPLIER_ID,
    TRIM(SUPPLIER_NAME) AS SUPPLIER_NAME,
    TRIM(PRODUCT_CATEGORY) AS PRODUCT_CATEGORY,
    TRIM(REGION) AS REGION,
    TRIM(COUNTRY) AS COUNTRY,
    TRIM(CITY) AS CITY,
    LEAD_TIME,
    RELIABILITY_SCORE,
    TRIM(QUALITY_RATING) AS QUALITY_RATING
FROM ANYCOMPANY_LAB.BRONZE.SUPPLIER_INFORMATION
WHERE SUPPLIER_ID IS NOT NULL
  AND LEAD_TIME > 0
  AND RELIABILITY_SCORE BETWEEN 0 AND 1
QUALIFY ROW_NUMBER() OVER (PARTITION BY SUPPLIER_ID ORDER BY RELIABILITY_SCORE DESC) = 1;

-- ============================================================
-- 11. EMPLOYEE_RECORDS_CLEAN
-- ============================================================
CREATE OR REPLACE TABLE ANYCOMPANY_LAB.SILVER.EMPLOYEE_RECORDS_CLEAN AS
SELECT
    EMPLOYEE_ID,
    TRIM(NAME) AS NAME,
    DATE_OF_BIRTH,
    HIRE_DATE,
    TRIM(DEPARTMENT) AS DEPARTMENT,
    TRIM(JOB_TITLE) AS JOB_TITLE,
    SALARY,
    TRIM(REGION) AS REGION,
    TRIM(COUNTRY) AS COUNTRY,
    TRIM(EMAIL) AS EMAIL
FROM ANYCOMPANY_LAB.BRONZE.EMPLOYEE_RECORDS
WHERE EMPLOYEE_ID IS NOT NULL
  AND SALARY > 0
  AND HIRE_DATE IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID ORDER BY HIRE_DATE DESC) = 1;

-- ============================================================
-- Vérification des tables SILVER
-- ============================================================
SELECT 'FINANCIAL_TRANSACTIONS_CLEAN' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM ANYCOMPANY_LAB.SILVER.FINANCIAL_TRANSACTIONS_CLEAN
UNION ALL SELECT 'PROMOTIONS_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.PROMOTIONS_CLEAN
UNION ALL SELECT 'MARKETING_CAMPAIGNS_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN
UNION ALL SELECT 'CUSTOMER_DEMOGRAPHICS_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.CUSTOMER_DEMOGRAPHICS_CLEAN
UNION ALL SELECT 'CUSTOMER_SERVICE_INTERACTIONS_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.CUSTOMER_SERVICE_INTERACTIONS_CLEAN
UNION ALL SELECT 'PRODUCT_REVIEWS_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.PRODUCT_REVIEWS_CLEAN
UNION ALL SELECT 'INVENTORY_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.INVENTORY_CLEAN
UNION ALL SELECT 'STORE_LOCATIONS_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.STORE_LOCATIONS_CLEAN
UNION ALL SELECT 'LOGISTICS_AND_SHIPPING_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.LOGISTICS_AND_SHIPPING_CLEAN
UNION ALL SELECT 'SUPPLIER_INFORMATION_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.SUPPLIER_INFORMATION_CLEAN
UNION ALL SELECT 'EMPLOYEE_RECORDS_CLEAN', COUNT(*) FROM ANYCOMPANY_LAB.SILVER.EMPLOYEE_RECORDS_CLEAN;
