-- ============================================================
-- Phase 1 – Étapes 1 à 4 : Préparation, Création, Chargement, Vérification
-- ============================================================

-- ============================================================
-- ÉTAPE 1 : Préparation de l'environnement Snowflake
-- ============================================================

CREATE DATABASE IF NOT EXISTS ANYCOMPANY_LAB;

USE DATABASE ANYCOMPANY_LAB;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;

USE SCHEMA BRONZE;

CREATE OR REPLACE STAGE S3_FOOD_BEVERAGE
  URL = 's3://logbrain-datalake/datasets/food-beverage/'
  FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

-- ============================================================
-- ÉTAPE 2 : Création des tables BRONZE
-- ============================================================

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.CUSTOMER_DEMOGRAPHICS (
    CUSTOMER_ID       VARCHAR,
    NAME              VARCHAR,
    DATE_OF_BIRTH     DATE,
    GENDER            VARCHAR,
    REGION            VARCHAR,
    COUNTRY           VARCHAR,
    CITY              VARCHAR,
    MARITAL_STATUS    VARCHAR,
    ANNUAL_INCOME     NUMBER(12,2)
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.CUSTOMER_SERVICE_INTERACTIONS (
    INTERACTION_ID        VARCHAR,
    INTERACTION_DATE      DATE,
    INTERACTION_TYPE      VARCHAR,
    ISSUE_CATEGORY        VARCHAR,
    DESCRIPTION           VARCHAR(5000),
    DURATION_MINUTES      NUMBER,
    RESOLUTION_STATUS     VARCHAR,
    FOLLOW_UP_REQUIRED    VARCHAR,
    CUSTOMER_SATISFACTION NUMBER
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.FINANCIAL_TRANSACTIONS (
    TRANSACTION_ID    VARCHAR,
    TRANSACTION_DATE  DATE,
    TRANSACTION_TYPE  VARCHAR,
    AMOUNT            NUMBER(12,2),
    PAYMENT_METHOD    VARCHAR,
    ENTITY            VARCHAR,
    REGION            VARCHAR,
    ACCOUNT_CODE      VARCHAR
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.PROMOTIONS_DATA (
    PROMOTION_ID          VARCHAR,
    PRODUCT_CATEGORY      VARCHAR,
    PROMOTION_TYPE        VARCHAR,
    DISCOUNT_PERCENTAGE   NUMBER(5,2),
    START_DATE            DATE,
    END_DATE              DATE,
    REGION                VARCHAR
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.MARKETING_CAMPAIGNS (
    CAMPAIGN_ID       VARCHAR,
    CAMPAIGN_NAME     VARCHAR,
    CAMPAIGN_TYPE     VARCHAR,
    PRODUCT_CATEGORY  VARCHAR,
    TARGET_AUDIENCE   VARCHAR,
    START_DATE        DATE,
    END_DATE          DATE,
    REGION            VARCHAR,
    BUDGET            NUMBER(12,2),
    REACH             NUMBER,
    CONVERSION_RATE   NUMBER(6,4)
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.PRODUCT_REVIEWS (
    REVIEW_ID           NUMBER,
    PRODUCT_ID          VARCHAR,
    REVIEWER_ID         VARCHAR,
    REVIEWER_NAME       VARCHAR,
    HELPFUL_VOTES       NUMBER,
    TOTAL_VOTES         NUMBER,
    RATING              NUMBER,
    REVIEW_DATE         TIMESTAMP,
    REVIEW_TITLE        VARCHAR,
    REVIEW_TEXT          VARCHAR(10000),
    PRODUCT_CATEGORY    VARCHAR,
    PRODUCT_SUBCATEGORY VARCHAR,
    PRODUCT_DESCRIPTION VARCHAR(5000)
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.INVENTORY (
    RAW_JSON VARIANT
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.STORE_LOCATIONS (
    RAW_JSON VARIANT
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.LOGISTICS_AND_SHIPPING (
    SHIPMENT_ID          VARCHAR,
    ORDER_ID             VARCHAR,
    SHIP_DATE            DATE,
    ESTIMATED_DELIVERY   DATE,
    SHIPPING_METHOD      VARCHAR,
    STATUS               VARCHAR,
    SHIPPING_COST        NUMBER(10,2),
    DESTINATION_REGION   VARCHAR,
    DESTINATION_COUNTRY  VARCHAR,
    CARRIER              VARCHAR
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.SUPPLIER_INFORMATION (
    SUPPLIER_ID        VARCHAR,
    SUPPLIER_NAME      VARCHAR,
    PRODUCT_CATEGORY   VARCHAR,
    REGION             VARCHAR,
    COUNTRY            VARCHAR,
    CITY               VARCHAR,
    LEAD_TIME          NUMBER,
    RELIABILITY_SCORE  NUMBER(4,2),
    QUALITY_RATING     VARCHAR
);

CREATE OR REPLACE TABLE ANYCOMPANY_LAB.BRONZE.EMPLOYEE_RECORDS (
    EMPLOYEE_ID    VARCHAR,
    NAME           VARCHAR,
    DATE_OF_BIRTH  DATE,
    HIRE_DATE      DATE,
    DEPARTMENT     VARCHAR,
    JOB_TITLE      VARCHAR,
    SALARY         NUMBER(12,2),
    REGION         VARCHAR,
    COUNTRY        VARCHAR,
    EMAIL          VARCHAR
);

-- ============================================================
-- ÉTAPE 3 : Chargement des données avec COPY INTO
-- ============================================================

-- CSV files
COPY INTO ANYCOMPANY_LAB.BRONZE.CUSTOMER_DEMOGRAPHICS
FROM @S3_FOOD_BEVERAGE/customer_demographics.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

COPY INTO ANYCOMPANY_LAB.BRONZE.CUSTOMER_SERVICE_INTERACTIONS
FROM @S3_FOOD_BEVERAGE/customer_service_interactions.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

COPY INTO ANYCOMPANY_LAB.BRONZE.FINANCIAL_TRANSACTIONS
FROM @S3_FOOD_BEVERAGE/financial_transactions.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

COPY INTO ANYCOMPANY_LAB.BRONZE.PROMOTIONS_DATA
FROM @S3_FOOD_BEVERAGE/promotions-data.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

COPY INTO ANYCOMPANY_LAB.BRONZE.MARKETING_CAMPAIGNS
FROM @S3_FOOD_BEVERAGE/marketing_campaigns.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

COPY INTO ANYCOMPANY_LAB.BRONZE.PRODUCT_REVIEWS
FROM @S3_FOOD_BEVERAGE/product_reviews.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = '\t' SKIP_HEADER = 0 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- JSON files (stage format override)
CREATE OR REPLACE STAGE S3_FOOD_BEVERAGE_JSON
  URL = 's3://logbrain-datalake/datasets/food-beverage/'
  FILE_FORMAT = (TYPE = 'JSON');

COPY INTO ANYCOMPANY_LAB.BRONZE.INVENTORY
FROM @S3_FOOD_BEVERAGE_JSON/inventory.json
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

COPY INTO ANYCOMPANY_LAB.BRONZE.STORE_LOCATIONS
FROM @S3_FOOD_BEVERAGE_JSON/store_locations.json
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

COPY INTO ANYCOMPANY_LAB.BRONZE.LOGISTICS_AND_SHIPPING
FROM @S3_FOOD_BEVERAGE/logistics_and_shipping.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

COPY INTO ANYCOMPANY_LAB.BRONZE.SUPPLIER_INFORMATION
FROM @S3_FOOD_BEVERAGE/supplier_information.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

COPY INTO ANYCOMPANY_LAB.BRONZE.EMPLOYEE_RECORDS
FROM @S3_FOOD_BEVERAGE/employee_records.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

-- ============================================================
-- ÉTAPE 4 : Vérifications
-- ============================================================

SELECT 'CUSTOMER_DEMOGRAPHICS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM ANYCOMPANY_LAB.BRONZE.CUSTOMER_DEMOGRAPHICS
UNION ALL SELECT 'CUSTOMER_SERVICE_INTERACTIONS', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.CUSTOMER_SERVICE_INTERACTIONS
UNION ALL SELECT 'FINANCIAL_TRANSACTIONS', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.FINANCIAL_TRANSACTIONS
UNION ALL SELECT 'PROMOTIONS_DATA', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.PROMOTIONS_DATA
UNION ALL SELECT 'MARKETING_CAMPAIGNS', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.MARKETING_CAMPAIGNS
UNION ALL SELECT 'PRODUCT_REVIEWS', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.PRODUCT_REVIEWS
UNION ALL SELECT 'INVENTORY', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.INVENTORY
UNION ALL SELECT 'STORE_LOCATIONS', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.STORE_LOCATIONS
UNION ALL SELECT 'LOGISTICS_AND_SHIPPING', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.LOGISTICS_AND_SHIPPING
UNION ALL SELECT 'SUPPLIER_INFORMATION', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.SUPPLIER_INFORMATION
UNION ALL SELECT 'EMPLOYEE_RECORDS', COUNT(*) FROM ANYCOMPANY_LAB.BRONZE.EMPLOYEE_RECORDS;

-- Échantillons
SELECT * FROM ANYCOMPANY_LAB.BRONZE.CUSTOMER_DEMOGRAPHICS LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.CUSTOMER_SERVICE_INTERACTIONS LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.FINANCIAL_TRANSACTIONS LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.PROMOTIONS_DATA LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.MARKETING_CAMPAIGNS LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.PRODUCT_REVIEWS LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.INVENTORY LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.STORE_LOCATIONS LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.LOGISTICS_AND_SHIPPING LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.SUPPLIER_INFORMATION LIMIT 10;
SELECT * FROM ANYCOMPANY_LAB.BRONZE.EMPLOYEE_RECORDS LIMIT 10;
