-- ============================================================
-- Phase 2 – Analyse de l'impact des promotions
-- ============================================================

-- 1. Vue d'ensemble des promotions
SELECT
    PRODUCT_CATEGORY,
    PROMOTION_TYPE,
    COUNT(*) AS NB_PROMOTIONS,
    AVG(DISCOUNT_PERCENTAGE) AS DISCOUNT_MOYEN,
    MIN(START_DATE) AS PREMIERE_PROMO,
    MAX(END_DATE) AS DERNIERE_PROMO
FROM ANYCOMPANY_LAB.SILVER.PROMOTIONS_CLEAN
GROUP BY 1, 2
ORDER BY NB_PROMOTIONS DESC;

-- 2. Promotions par région
SELECT
    REGION,
    COUNT(*) AS NB_PROMOTIONS,
    AVG(DISCOUNT_PERCENTAGE) AS DISCOUNT_MOYEN
FROM ANYCOMPANY_LAB.SILVER.PROMOTIONS_CLEAN
GROUP BY 1
ORDER BY NB_PROMOTIONS DESC;

-- 3. Ventes pendant vs hors période de promotion
-- (Comparaison des ventes financières pendant les périodes de promo actives)
SELECT
    CASE WHEN p.PROMOTION_ID IS NOT NULL THEN 'Avec promotion' ELSE 'Sans promotion' END AS CONTEXTE_PROMO,
    COUNT(*) AS NB_TRANSACTIONS,
    SUM(ft.AMOUNT) AS TOTAL_VENTES,
    AVG(ft.AMOUNT) AS PANIER_MOYEN
FROM ANYCOMPANY_LAB.SILVER.FINANCIAL_TRANSACTIONS_CLEAN ft
LEFT JOIN ANYCOMPANY_LAB.SILVER.PROMOTIONS_CLEAN p
    ON ft.REGION = p.REGION
    AND ft.TRANSACTION_DATE BETWEEN p.START_DATE AND p.END_DATE
WHERE ft.TRANSACTION_TYPE = 'Sale'
GROUP BY 1
ORDER BY 1;

-- 4. Sensibilité des catégories aux promotions (via campagnes marketing)
SELECT
    p.PRODUCT_CATEGORY,
    p.PROMOTION_TYPE,
    AVG(p.DISCOUNT_PERCENTAGE) AS DISCOUNT_MOYEN,
    COUNT(DISTINCT p.PROMOTION_ID) AS NB_PROMOS,
    COUNT(DISTINCT mc.CAMPAIGN_ID) AS NB_CAMPAGNES_ASSOCIEES
FROM ANYCOMPANY_LAB.SILVER.PROMOTIONS_CLEAN p
LEFT JOIN ANYCOMPANY_LAB.SILVER.MARKETING_CAMPAIGNS_CLEAN mc
    ON p.PRODUCT_CATEGORY = mc.PRODUCT_CATEGORY
    AND p.REGION = mc.REGION
    AND mc.START_DATE BETWEEN p.START_DATE AND p.END_DATE
GROUP BY 1, 2
ORDER BY NB_PROMOS DESC;

-- 5. Distribution temporelle des promotions
SELECT
    YEAR(START_DATE) AS ANNEE,
    QUARTER(START_DATE) AS TRIMESTRE,
    COUNT(*) AS NB_PROMOTIONS,
    AVG(DISCOUNT_PERCENTAGE) AS DISCOUNT_MOYEN,
    AVG(DATEDIFF('DAY', START_DATE, END_DATE)) AS DUREE_MOYENNE_JOURS
FROM ANYCOMPANY_LAB.SILVER.PROMOTIONS_CLEAN
GROUP BY 1, 2
ORDER BY 1, 2;
