-- ============================================================
-- Phase 2 – Analyses exploratoires et business
-- ============================================================

-- ============================================================
-- 2.1 – Évolution des ventes dans le temps
-- ============================================================

-- Ventes mensuelles (transactions de type 'Sale')
SELECT
    DATE_TRUNC('MONTH', TRANSACTION_DATE) AS MOIS,
    COUNT(*) AS NB_TRANSACTIONS,
    SUM(AMOUNT) AS TOTAL_VENTES,
    AVG(AMOUNT) AS PANIER_MOYEN
FROM ANYCOMPANY_LAB.SILVER.FINANCIAL_TRANSACTIONS_CLEAN
WHERE TRANSACTION_TYPE = 'Sale'
GROUP BY 1
ORDER BY 1;

-- Ventes annuelles
SELECT
    YEAR(TRANSACTION_DATE) AS ANNEE,
    COUNT(*) AS NB_TRANSACTIONS,
    SUM(AMOUNT) AS TOTAL_VENTES,
    AVG(AMOUNT) AS PANIER_MOYEN
FROM ANYCOMPANY_LAB.SILVER.FINANCIAL_TRANSACTIONS_CLEAN
WHERE TRANSACTION_TYPE = 'Sale'
GROUP BY 1
ORDER BY 1;

-- Ventes par région
SELECT
    REGION,
    COUNT(*) AS NB_TRANSACTIONS,
    SUM(AMOUNT) AS TOTAL_VENTES,
    AVG(AMOUNT) AS PANIER_MOYEN
FROM ANYCOMPANY_LAB.SILVER.FINANCIAL_TRANSACTIONS_CLEAN
WHERE TRANSACTION_TYPE = 'Sale'
GROUP BY 1
ORDER BY TOTAL_VENTES DESC;

-- Performance par type de transaction
SELECT
    TRANSACTION_TYPE,
    COUNT(*) AS NB_TRANSACTIONS,
    SUM(AMOUNT) AS TOTAL_MONTANT,
    AVG(AMOUNT) AS MONTANT_MOYEN
FROM ANYCOMPANY_LAB.SILVER.FINANCIAL_TRANSACTIONS_CLEAN
GROUP BY 1
ORDER BY TOTAL_MONTANT DESC;

-- ============================================================
-- 2.2 – Répartition clients par segments démographiques
-- ============================================================

-- Par genre
SELECT
    GENDER,
    COUNT(*) AS NB_CLIENTS,
    AVG(ANNUAL_INCOME) AS REVENU_MOYEN
FROM ANYCOMPANY_LAB.SILVER.CUSTOMER_DEMOGRAPHICS_CLEAN
GROUP BY 1
ORDER BY NB_CLIENTS DESC;

-- Par région
SELECT
    REGION,
    COUNT(*) AS NB_CLIENTS,
    AVG(ANNUAL_INCOME) AS REVENU_MOYEN
FROM ANYCOMPANY_LAB.SILVER.CUSTOMER_DEMOGRAPHICS_CLEAN
GROUP BY 1
ORDER BY NB_CLIENTS DESC;

-- Par statut marital
SELECT
    MARITAL_STATUS,
    COUNT(*) AS NB_CLIENTS,
    AVG(ANNUAL_INCOME) AS REVENU_MOYEN
FROM ANYCOMPANY_LAB.SILVER.CUSTOMER_DEMOGRAPHICS_CLEAN
GROUP BY 1
ORDER BY NB_CLIENTS DESC;

-- Tranches d'âge
SELECT
    CASE
        WHEN DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 25 THEN '18-24'
        WHEN DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 35 THEN '25-34'
        WHEN DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 45 THEN '35-44'
        WHEN DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 55 THEN '45-54'
        WHEN DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) < 65 THEN '55-64'
        ELSE '65+'
    END AS TRANCHE_AGE,
    COUNT(*) AS NB_CLIENTS,
    AVG(ANNUAL_INCOME) AS REVENU_MOYEN
FROM ANYCOMPANY_LAB.SILVER.CUSTOMER_DEMOGRAPHICS_CLEAN
GROUP BY 1
ORDER BY 1;
